# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messageStructure.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16messageStructure.proto\"\x80\x01\n\x07Request\x12\x1c\n\x04stop\x18\x01 \x01(\x0b\x32\x0c.StopRequestH\x00\x12(\n\x05reset\x18\x02 \x01(\x0b\x32\x17.ResetBlockListsRequestH\x00\x12\"\n\x04\x65xpr\x18\x03 \x01(\x0b\x32\x12.ExpressionRequestH\x00\x42\t\n\x07request\"\r\n\x0bStopRequest\"\x18\n\x16ResetBlockListsRequest\"K\n\x11\x45xpressionRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x12\n\nexpression\x18\x03 \x01(\t\"\x85\x01\n\x08Response\x12\x1d\n\x04stop\x18\x01 \x01(\x0b\x32\r.StopResponseH\x00\x12)\n\x05reset\x18\x02 \x01(\x0b\x32\x18.ResetBlockListsResponseH\x00\x12#\n\x04\x65xpr\x18\x03 \x01(\x0b\x32\x13.ExpressionResponseH\x00\x42\n\n\x08response\"\x0e\n\x0cStopResponse\"\x19\n\x17ResetBlockListsResponse\";\n\x12\x45xpressionResponse\x12\x15\n\rauthenticated\x18\x01 \x01(\x08\x12\x0e\n\x06result\x18\x02 \x01(\tb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_STOPREQUEST = DESCRIPTOR.message_types_by_name['StopRequest']
_RESETBLOCKLISTSREQUEST = DESCRIPTOR.message_types_by_name['ResetBlockListsRequest']
_EXPRESSIONREQUEST = DESCRIPTOR.message_types_by_name['ExpressionRequest']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_STOPRESPONSE = DESCRIPTOR.message_types_by_name['StopResponse']
_RESETBLOCKLISTSRESPONSE = DESCRIPTOR.message_types_by_name['ResetBlockListsResponse']
_EXPRESSIONRESPONSE = DESCRIPTOR.message_types_by_name['ExpressionResponse']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'messageStructure_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

StopRequest = _reflection.GeneratedProtocolMessageType('StopRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOPREQUEST,
  '__module__' : 'messageStructure_pb2'
  # @@protoc_insertion_point(class_scope:StopRequest)
  })
_sym_db.RegisterMessage(StopRequest)

ResetBlockListsRequest = _reflection.GeneratedProtocolMessageType('ResetBlockListsRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESETBLOCKLISTSREQUEST,
  '__module__' : 'messageStructure_pb2'
  # @@protoc_insertion_point(class_scope:ResetBlockListsRequest)
  })
_sym_db.RegisterMessage(ResetBlockListsRequest)

ExpressionRequest = _reflection.GeneratedProtocolMessageType('ExpressionRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXPRESSIONREQUEST,
  '__module__' : 'messageStructure_pb2'
  # @@protoc_insertion_point(class_scope:ExpressionRequest)
  })
_sym_db.RegisterMessage(ExpressionRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'messageStructure_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

StopResponse = _reflection.GeneratedProtocolMessageType('StopResponse', (_message.Message,), {
  'DESCRIPTOR' : _STOPRESPONSE,
  '__module__' : 'messageStructure_pb2'
  # @@protoc_insertion_point(class_scope:StopResponse)
  })
_sym_db.RegisterMessage(StopResponse)

ResetBlockListsResponse = _reflection.GeneratedProtocolMessageType('ResetBlockListsResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESETBLOCKLISTSRESPONSE,
  '__module__' : 'messageStructure_pb2'
  # @@protoc_insertion_point(class_scope:ResetBlockListsResponse)
  })
_sym_db.RegisterMessage(ResetBlockListsResponse)

ExpressionResponse = _reflection.GeneratedProtocolMessageType('ExpressionResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXPRESSIONRESPONSE,
  '__module__' : 'messageStructure_pb2'
  # @@protoc_insertion_point(class_scope:ExpressionResponse)
  })
_sym_db.RegisterMessage(ExpressionResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=27
  _REQUEST._serialized_end=155
  _STOPREQUEST._serialized_start=157
  _STOPREQUEST._serialized_end=170
  _RESETBLOCKLISTSREQUEST._serialized_start=172
  _RESETBLOCKLISTSREQUEST._serialized_end=196
  _EXPRESSIONREQUEST._serialized_start=198
  _EXPRESSIONREQUEST._serialized_end=273
  _RESPONSE._serialized_start=276
  _RESPONSE._serialized_end=409
  _STOPRESPONSE._serialized_start=411
  _STOPRESPONSE._serialized_end=425
  _RESETBLOCKLISTSRESPONSE._serialized_start=427
  _RESETBLOCKLISTSRESPONSE._serialized_end=452
  _EXPRESSIONRESPONSE._serialized_start=454
  _EXPRESSIONRESPONSE._serialized_end=513
# @@protoc_insertion_point(module_scope)
